name: Cleanup Docker Images

# Allow this workflow to be triggered manually
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to clean up Docker images for'
        required: true
        default: 'master'


jobs:
  delete-container-versions:
    uses: .github/workflows/delete-container-versions.yml
    with:
      package_name: 'elexis-server'
      package_type: 'container'
